### ISSUE TITLE
4.13.2 palyground lauch error

### ISSUE THREAD

**Issue by tlightsky** [ncsoft/Unreal.js#134]
```[2016.12.26-06.58.50:446][  0]LogSavePackage: Save=13.50ms
[2016.12.26-06.58.50:446][  0]LogSavePackage: Async saving from memory to '/Users/me/Documents/source/games/Unreal.js/Examples/Saved/Cooked/MacNoEditor/Engine/Content/EngineSky/T_Sky_Clouds_M.uasset'
[2016.12.26-06.58.50:446][  0]LogSavePackage:Display: Finished SavePackage /Users/me/Documents/source/games/Unreal.js/Examples/Saved/Cooked/MacNoEditor/Engine/Content/EngineSky/T_Sky_Clouds_M.uasset
JavascriptPlayground: [2016.12.26-06.58.50:467][  0]LogIOS:Display: Got a bulk data texture, with 1 mips/Users/me/Documents/source/games/Unreal.js/Examples/Saved/StagedBuilds/MacNoEditor/JavascriptPlayground/Content/Scripts/aliases.js:40785: Uncaught ReferenceError: FunctionalTestingManager is not defined
JavascriptPlayground: Javascript:Error: /Users/me/Documents/source/games/Unreal.js/Examples/Saved/StagedBuilds/MacNoEditor/JavascriptPlayground/Content/Scripts/aliases.js:258: ReferenceError: FunctionalTestingManager is not defined
JavascriptPlayground:
JavascriptPlayground: [2016.12.26-06.58.51:418][  0]Javascript:Error: /Users/me/Documents/source/games/Unreal.js/Examples/Saved/StagedBuilds/MacNoEditor/JavascriptPlayground/Content/Scripts/aliases.js:258: ReferenceError: FunctionalTestingManager is not definedJavascript:Error: ReferenceError: FunctionalTestingManager is not defined
JavascriptPlayground:
JavascriptPlayground: [2016.12.26-06.58.51:418][  0]Javascript:Error: ReferenceError: FunctionalTestingManager is not definedJavascript:Error:     at /Users/me/Documents/source/games/Unreal.js/Examples/Saved/StagedBuilds/MacNoEditor/JavascriptPlayground/Content/Scripts/aliases.js:258:56
JavascriptPlayground:
JavascriptPlayground: [2016.12.26-06.58.51:419][  0]Javascript:Error:     at /Users/me/Documents/source/games/Unreal.js/Examples/Saved/StagedBuilds/MacNoEditor/JavascriptPlayground/Content/Scripts/aliases.js:258:56Javascript:Error:     at /Users/me/Documents/source/games/Unreal.js/Examples/Saved/StagedBuilds/MacNoEditor/JavascriptPlayground/Content/Scripts/aliases.js:1323:3
JavascriptPlayground:
JavascriptPlayground: [2016.12.26-06.58.51:419][  0]Javascript:Error:     at /Users/me/Documents/source/games/Unreal.js/Examples/Saved/StagedBuilds/MacNoEditor/JavascriptPlayground/Content/Scripts/aliases.js:1323:3Javascript:Error:     at module.exports (/Users/me/Documents/source/games/Unreal.js/Examples/Saved/StagedBuilds/MacNoEditor/JavascriptPlayground/Content/Scripts/bootstrap.js:8:17)
JavascriptPlayground:
JavascriptPlayground: [2016.12.26-06.58.51:419][  0]Javascript:Error:     at module.exports (/Users/me/Documents/source/games/Unreal.js/Examples/Saved/StagedBuilds/MacNoEditor/JavascriptPlayground/Content/Scripts/bootstrap.js:8:17)Javascript:Error:     at /Users/me/Documents/source/games/Unreal.js/Examples/Saved/StagedBuilds/MacNoEditor/JavascriptPlayground/Content/Scripts/helloWorld.js:34:25
JavascriptPlayground:
JavascriptPlayground: [2016.12.26-06.58.51:419][  0]Javascript:Error:     at /Users/me/Documents/source/games/Unreal.js/Examples/Saved/StagedBuilds/MacNoEditor/JavascriptPlayground/Content/Scripts/helloWorld.js:34:25Javascript:Error:     at /Users/me/Documents/source/games/Unreal.js/Examples/Saved/StagedBuilds/MacNoEditor/JavascriptPlayground/Content/Scripts/helloWorld.js:37:3
JavascriptPlayground:
JavascriptPlayground: [2016.12.26-06.58.51:419][  0]Javascript:Error:     at /Users/me/Documents/source/games/Unreal.js/Examples/Saved/StagedBuilds/MacNoEditor/JavascriptPlayground/Content/Scripts/helloWorld.js:37:3LogGameMode:Display: Match State Changed from EnteringMap to WaitingToStart
JavascriptPlayground:
JavascriptPlayground: [2016.12.26-06.58.51:498][  0]LogGameMode:Display: Match State Changed from EnteringMap to WaitingToStartLogGameMode:Display: Match State Changed from WaitingToStart to InProgress
JavascriptPlayground:
JavascriptPlayground: [2016.12.26-06.58.51:498][  0]LogGameMode:Display: Match State Changed from WaitingToStart to InProgressLogOnline:Display: Unloading online subsystem: NULL
JavascriptPlayground:
JavascriptPlayground: [2016.12.26-07.06.34:369][880]LogOnline:Display: Unloading online subsystem: NULLLogHttp:Display: Http module shutting down, but needs to wait on 1 outstanding Http requests:```

**Comment by nakosung** [comment]
This error is fixed by https://github.com/ncsoft/Unreal.js-core/commit/61006b82eae2edb3b0d4d085afdb159941b94c4a. But marketplace version isn't updated yet.
