### ISSUE TITLE
UE4.17.1 Source Build - GWorld is not defined.

### ISSUE THREAD

**Issue by xemjeff** [ncsoft/Unreal.js#190]
I get an error when trying to run any of the example scripts.

```
Context.RunFile("HelloCanvas.js")
< undefined
Error: file:///c:/Code/UnrealJS/Content/Scripts/helloCanvas.js:8: ReferenceError: GWorld is not defined
Error: ReferenceError: GWorld is not defined
Error:     at GetPC (file:///c:/Code/UnrealJS/Content/Scripts/helloCanvas.js:8:35)
Error:     at main (file:///c:/Code/UnrealJS/Content/Scripts/helloCanvas.js:13:9)
Error:     at process.nextTick (file:///c:/Code/UnrealJS/Content/Scripts/helloCanvas.js:56:46)
Error:     at invoke_next (file:///c:/Code/UnrealJS/Plugins/UnrealJS/Content/Scripts/polyfill/timers.js:14:9)
Error:     at Array.forEach (<anonymous>)
Error:     at Object.flushTicks (file:///c:/Code/UnrealJS/Plugins/UnrealJS/Content/Scripts/polyfill/timers.js:36:18)
Error:     at root (file:///c:/Code/UnrealJS/Plugins/UnrealJS/Content/Scripts/polyfill/timers.js:20:24)
```
I have downloaded the plugin source from git hub, placed in my project's Plugin folder and rebuilt when launching the project. The plugin shows up and the JavascriptConsole works.

Is there something simple that I'm missing?

**Comment by crocuis** [comment]
In Context.RunFile, JavascriptContext does not have GWorld. Use an api like require (...).

**Comment by ghm86** [comment]
in.
\UnrealJS\Source\V8\Private\TypingGenerator.h
add   new function

void ExportUserAdd(FString name, FString value)
	{
		TokenWriter w(*this); 
		w.push("declare var ");
		w.push(name);
		w.push(" : ");
		w.push(value);
		w.push(";\n\n");

		Text.Append(*w);
	}


in \UnrealJS\Source\V8\Private\JavascriptContext_Private.cpp

add code in function
bool WriteDTS(const FString& Filename, bool bIncludingTooltip)




bool WriteDTS(const FString& Filename, bool bIncludingTooltip)
	{
#if WITH_EDITOR
		TypingGenerator instance(*(Environment.Get()));

		instance.no_tooltip = !bIncludingTooltip;

		instance.ExportBootstrap();

		for (auto it = Environment->ClassToFunctionTemplateMap.CreateConstIterator(); it; ++it)
		{
			instance.Export(it.Key());
		}

		for (auto pair : WKOs)
		{
			auto k = pair.Key;
			auto v = pair.Value;

			instance.ExportWKO(k, v);
		}
 
		instance.ExportUserAdd(TEXT("GWorld"), TEXT("World"));      //add code 

		instance.Finalize();

		return instance.Save(Filename);
#else
		return false;
#endif
	}
