### ISSUE TITLE
fs is not defined

### ISSUE THREAD

**Issue by Bdoom** [ncsoft/Unreal.js#284]
How did you fix this in? #52 

```
Javascript: Error: file:///../../../../Users/decil/Desktop/HVS_Game/Content/Scripts/VoiceChat.js:60: TypeError: require(...)(...) is not a function
Javascript: Error: TypeError: require(...)(...) is not a function
Javascript: Error:     at file:///../../../../Users/decil/Desktop/HVS_Game/Content/Scripts/VoiceChat.js:60:38
Javascript: Error:     at file:///../../../../Users/decil/Desktop/HVS_Game/Content/Scripts/VoiceChat.js:62:3
Javascript: Error: file:///c:/Users/decil/Desktop/HVS_Game/Content/Scripts/VoiceChat.js:23: ReferenceError: fs is not defined
Javascript: Error: ReferenceError: fs is not defined
Javascript: Error:     at main (file:///c:/Users/decil/Desktop/HVS_Game/Content/Scripts/VoiceChat.js:23:14)
Javascript: Error:     at file:///c:/Users/decil/Desktop/HVS_Game/Content/Scripts/VoiceChat.js:52:42
Javascript: Error:     at invoke_next (file:///../../../../Users/decil/Desktop/HVS_Game/Plugins/UnrealJS/Content/Scripts/polyfill/timers.js:14:9)
Javascript: Error:     at Array.forEach (<anonymous>)
Javascript: Error:     at Object.flushTicks (file:///../../../../Users/decil/Desktop/HVS_Game/Plugins/UnrealJS/Content/Scripts/polyfill/timers.js:36:18)
Javascript: Error:     at root (file:///../../../../Users/decil/Desktop/HVS_Game/Plugins/UnrealJS/Content/Scripts/polyfill/timers.js:20:24)
```

**Comment by crocuis** [comment]
Since unreal.js is not dependent on node.js, you cannot use modules like 'fs'.
