### ISSUE TITLE
FYI 2048 demo now broken

### ISSUE THREAD

**Issue by Youdaman** [ncsoft/Unreal.js#30]
The demo worked with previous builds, but now I get the following error:

```
Error: c:\Users\Stew\Desktop\Unreal.js\Examples\Content\Scripts\2048\game\local_storage_manager.js:1: ReferenceError: window is not defined
Error: ReferenceError: window is not defined
Error:     at c:\Users\Stew\Desktop\Unreal.js\Examples\Content\Scripts\2048\game\local_storage_manager.js:1:1
Error:     at c:\Users\Stew\Desktop\Unreal.js\Examples\Content\Scripts\2048\game\local_storage_manager.js:67:25
Error:     at module.exports (c:\Users\Stew\Desktop\Unreal.js\Examples\Content\Scripts\2048\game\application.js:7:35)
Error:     at start_game (c:\Users\Stew\Desktop\Unreal.js\Examples\Content\Scripts\2048\index.js:48:53)
Error:     at module.exports (c:\Users\Stew\Desktop\Unreal.js\Examples\Content\Scripts\2048\index.js:55:9)
Error:     at c:\Users\Stew\Desktop\Unreal.js\Examples\Content\Scripts\hello2048.js:10:27
Error:     at invoke_next (c:/Users/Stew/Desktop/Unreal.js/Examples/Plugins/UnrealJS/Content/Scripts/polyfill/timers.js:14:9)
Error:     at Array.forEach (native)
Error:     at Object.target.process.flushTicks (c:/Users/Stew/Desktop/Unreal.js/Examples/Plugins/UnrealJS/Content/Scripts/polyfill/timers.js:36:18)
Error:     at root (c:/Users/Stew/Desktop/Unreal.js/Examples/Plugins/UnrealJS/Content/Scripts/polyfill/timers.js:20:24)
< Invalid script for require
Error: EXCEPTION TypeError: StorageManager is not a function TypeError: StorageManager is not a function
    at new GameManager (c:\Users\Stew\Desktop\Unreal.js\Examples\Content\Scripts\2048\game\game_manager.js:7:25)
    at module.exports (c:\Users\Stew\Desktop\Unreal.js\Examples\Content\Scripts\2048\game\application.js:11:20)
    at start_game (c:\Users\Stew\Desktop\Unreal.js\Examples\Content\Scripts\2048\index.js:48:53)
    at module.exports (c:\Users\Stew\Desktop\Unreal.js\Examples\Content\Scripts\2048\index.js:55:9)
    at c:\Users\Stew\Desktop\Unreal.js\Examples\Content\Scripts\hello2048.js:10:27
    at invoke_next (c:/Users/Stew/Desktop/Unreal.js/Examples/Plugins/UnrealJS/Content/Scripts/polyfill/timers.js:14:9)
    at Array.forEach (native)
    at Object.target.process.flushTicks (c:/Users/Stew/Desktop/Unreal.js/Examples/Plugins/UnrealJS/Content/Scripts/polyfill/timers.js:36:18)
    at root (c:/Users/Stew/Desktop/Unreal.js/Examples/Plugins/UnrealJS/Content/Scripts/polyfill/timers.js:20:24)
```

I'm guessing it's some module wanting a browser window object for localStorage?

**Comment by nakosung** [comment]
fixed at d3d98b8. Thank you!
