### ISSUE TITLE
helloSpringy.js example not downloading additioanl dependencies

### ISSUE THREAD

**Issue by dgan11** [ncsoft/Unreal.js#317]
Hello trying to run the I have copied the example repo and am trying to run the helloSpringy.js code on an empty actor but I am getting these error messages

`Error: file:////Users/davidgan/Desktop/UEAuthDemo/UEAuthDemo/Content/Scripts/node_modules/bootstrap/dist/js/bootstrap.js:761: ReferenceError: document is not defined
Error: ReferenceError: document is not defined
Error:     at enableDismissTrigger (file:////Users/davidgan/Desktop/UEAuthDemo/UEAuthDemo/Content/Scripts/node_modules/bootstrap/dist/js/bootstrap.js:761:21)
Error:     at file:////Users/davidgan/Desktop/UEAuthDemo/UEAuthDemo/Content/Scripts/node_modules/bootstrap/dist/js/bootstrap.js:856:3
Error:     at file:////Users/davidgan/Desktop/UEAuthDemo/UEAuthDemo/Content/Scripts/node_modules/bootstrap/dist/js/bootstrap.js:7:83
Error:     at file:////Users/davidgan/Desktop/UEAuthDemo/UEAuthDemo/Content/Scripts/node_modules/bootstrap/dist/js/bootstrap.js:10:3
Error:     at file:////Users/davidgan/Desktop/UEAuthDemo/UEAuthDemo/Content/Scripts/node_modules/bootstrap/dist/js/bootstrap.js:5048:4
Error:     at file:////Users/davidgan/Desktop/UEAuthDemo/UEAuthDemo/Content/Scripts/node_modules/bootstrap/dist/js/bootstrap.js:5049:25
Error:     at file:///../../../../../../davidgan/Desktop/UEAuthDemo/UEAuthDemo/Content/Scripts/./ExampleScriptsFromUnrealJS/helloSpringy.js:210:5
Error:     at file:///../../../../../../davidgan/Desktop/UEAuthDemo/UEAuthDemo/Content/Scripts/./ExampleScriptsFromUnrealJS/helloSpringy.js:445:3
< Invalid script for require
Error: file:///../../../../../../davidgan/Desktop/UEAuthDemo/UEAuthDemo/Content/Scripts/./ExampleScriptsFromUnrealJS/helloSpringy.js:210: TypeError: require(...) is not a function
Error: TypeError: require(...) is not a function
Error:     at file:///../../../../../../davidgan/Desktop/UEAuthDemo/UEAuthDemo/Content/Scripts/./ExampleScriptsFromUnrealJS/helloSpringy.js:210:25
Error:     at file:///../../../../../../davidgan/Desktop/UEAuthDemo/UEAuthDemo/Content/Scripts/./ExampleScriptsFromUnrealJS/helloSpringy.js:445:3`

I have installed the Unreal.js plugin and it seems to be working with a test javascript file that just console.logs() something that doesnt use the try catch structure in helloSpringy

My helloSpringy.js looks exactly like [this](https://github.com/ncsoft/Unreal.js/blob/master/Examples/Content/Scripts/helloSpringy.js)

My Scripts folder looks like this (it includes bootstrap.js)
![Screen Shot 2022-02-09 at 10 58 39 AM](https://user-images.githubusercontent.com/37032548/153270952-f3745069-4147-448d-8b78-6016f10aaf90.png)

And my package.json file looks like this
`{
  "name": "unrealjs_examples",
  "version": "1.0.0",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "NCSOFT",
  "license": "ISC",
  "dependencies": {
    "bootstrap": "^5.1.3",
    "convnetjs": "^0.3.0",
    "springy": "^2.8.0"
  },
  "directories": {
    "test": "tests"
  },
  "description": ""
}
`

**Comment by dgan11** [comment]
I have also run an `npm install` in the Scripts folder to install existing dependencies
