### ISSUE TITLE
In UE4.10.4 2048 example run fail.

### ISSUE THREAD

**Issue by damody** [ncsoft/Unreal.js#34]
full log : https://gist.github.com/damody/a69db626e34709c72edd
```
Error: EXCEPTION TypeError: Cannot read property 'scope' of undefined TypeError: Cannot read property 'scope' of undefined
    at set_attrs (j:\C++\UnrealEngine-4.10.4-release\Engine\Plugins\UnrealJS\Content\Scripts\instantiator.js:239:40)
    at module.exports (j:\Unreal Projects\Unreal.js\Examples\Content\Scripts\2048\game\actuator.js:15:9)
    at module.exports (j:\Unreal Projects\Unreal.js\Examples\Content\Scripts\2048\game\application.js:6:45)
    at start_game (j:\Unreal Projects\Unreal.js\Examples\Content\Scripts\2048\index.js:48:53)
    at module.exports (j:\Unreal Projects\Unreal.js\Examples\Content\Scripts\2048\index.js:55:9)
    at j:\Unreal Projects\Unreal.js\Examples\Content\Scripts\hello2048.js:10:27
    at invoke_next (j:/C++/UnrealEngine-4.10.4-release/Engine/Plugins/UnrealJS/Content/Scripts/polyfill/timers.js:14:9)
    at Array.forEach (native)
    at Object.target.process.flushTicks (j:/C++/UnrealEngine-4.10.4-release/Engine/Plugins/UnrealJS/Content/Scripts/polyfill/timers.js:36:18)
    at root (j:/C++/UnrealEngine-4.10.4-release/Engine/Plugins/UnrealJS/Content/Scripts/polyfill/timers.js:20:24)
```
no problem for another examples.

I install node.js 5.7.0.

**Comment by nakosung** [comment]
2048 is broken since I optimized `UMG instantiator`. https://github.com/fuyushimoya/Unreal.js seems good.

**Comment by damody** [comment]
yes, it's work.
