### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by Youdaman** [ncsoft/Unreal.js#49]
I followed the guide here: https://github.com/ncsoft/Unreal.js/wiki/Cooking

And I copied the Scripts directory from the UnrealJS plugin Content directory to the Content directory of my freshly packaged project.

When I tried to run this my project didn't work as expected (the JS wasn't running).

So then I changed the following line:

`class MyPlayerController extends Blueprint.Load('/Game/ThirdPersonBP/Blueprints/RecoveryPlayerController').GeneratedClass {`

to:

`class MyPlayerController extends Root.ResolveClass('RecoveryPlayerController') {`

But the JS still doesn't run. The project launches, I just don't see the result of my JS as I do when I launch from the editor.

Here's the Scripts directory of the built game containing all of the scripts from the plugin's Content/Scripts as well as the scripts from my project's Content/Scripts:

![screenshot 2016-03-20 16 55 30](https://cloud.githubusercontent.com/assets/287330/13903066/b2d2c260-eebd-11e5-8419-81ad7e8085c7.png)

Any clues or corrections would be appreciated! :)

**Comment by Youdaman** [comment]
I followed your suggestions here: https://github.com/ncsoft/Unreal.js/issues/41#issuecomment-195810951

However that stopped things from building successfully (however it packages fine without these steps).

**Comment by Youdaman** [comment]
Nevermind I think I've worked it out. I started with a fresh project and added in my plugins, rebuilding as I went, and now I'm starting with a fresh JS script.

**Comment by Youdaman** [comment]
Actually it turns out the issue was this line:

`class MyPlayerController extends Root.ResolveClass('RecoveryPlayerController') {'

When I changed this to:

`class MyPlayerController extends PlayerController {`

Things worked (or at least I could see debug messages being printed to the screen via JS).

Now I'm onto working out why Steam doesn't load for this packaged version of the game when it does when I launch standalone from the editor...

**Comment by Youdaman** [comment]
None of these work in a packaged build:

```
class MyPlayerController extends Blueprint.Load('/Game/ThirdPersonBP/Blueprints/RecoveryPlayerController').GeneratedClass {
class MyPlayerController extends Root.ResolveClass('/Game/ThirdPersonBP/Blueprints/RecoveryPlayerController') {
class MyPlayerController extends Root.ResolveClass('RecoveryPlayerController') {
class MyPlayerController extends RecoveryPlayerController {
```

The first one however works when launching the game from the editor. I'm guessing the syntax has changed since the page in the wiki for Cooking was written? Or maybe I'm just missing something.

**Comment by nakosung** [comment]
Root.ResolveClass is the way. But it takes 'nick name' of registered class. You have to register your class in javascript component which is placed within your level actor.

**Comment by Youdaman** [comment]
Excellent! I added `RecoveryPlayerController` in the Class Assets property of the JavaScript Component of the Actor in my level and it ran properly when launched from the editor.

However it failed to package. I was thinking that it was because I was using the same name as the class for its nickname:

`class MyPlayerController extends Root.ResolveClass('RecoveryPlayerController') {`

So I changed the nickname in the Class Assets property to be `RecoveryPC` and again it worked when launched from the editor but it failed to package.

Here is the Output Log for the packaging process:

```
MainFrameActions: Packaging (Windows (64-bit)): Running AutomationTool...
MainFrameActions: Packaging (Windows (64-bit)): Program.Main: CWD=C:\Program Files\Epic Games\4.10\Engine\Binaries\DotNET
MainFrameActions: Packaging (Windows (64-bit)): Automation.ParseCommandLine: Parsing command line: BuildCookRun -rocket -nocompile -nocompileeditor -installed -nop4 -project=D:/Dropbox/AAA Recovery/Recovery/Recovery.uproject -cook -stage -archive -archivedirectory=C:/Users/Stew/Desktop -package -clientconfig=Development -ue4exe=UE4Editor-Cmd.exe -pak -prereqs -nodebuginfo -targetplatform=Win64 -build -CrashReporter -utf8output
MainFrameActions: Packaging (Windows (64-bit)): Automation.Process: IsBuildMachine=False
MainFrameActions: Packaging (Windows (64-bit)): Automation.Process: ShouldKillProcesses=True
MainFrameActions: Packaging (Windows (64-bit)): Automation.Process: Setting up command environment.
MainFrameActions: Packaging (Windows (64-bit)): CommandUtils.SetEnvVar: SetEnvVar uebp_EngineSavedFolder=C:/Program Files/Epic Games/4.10/Engine/Programs/AutomationTool/Saved
MainFrameActions: Packaging (Windows (64-bit)): CommandUtils.DeleteDirectoryContents: DeleteDirectoryContents(C:/Users/Stew/AppData/Roaming/Unreal Engine/AutomationTool/Logs/C+Program+Files+Epic+Games+4.10)
MainFrameActions: Packaging (Windows (64-bit)): WindowsHostPlatform.SetFrameworkVars: Setting .Net Framework environment variables.
MainFrameActions: Packaging (Windows (64-bit)): WindowsHostPlatform.SetFrameworkVars: Supports64bitExecutables=True
MainFrameActions: Packaging (Windows (64-bit)): WindowsHostPlatform.SetFrameworkVars: WindowsPlatform.CompilerVisualStudio2015
MainFrameActions: Packaging (Windows (64-bit)): WindowsHostPlatform.SetFrameworkVars: WindowsSDKDir=C:\Program Files (x86)\Windows Kits\8.1\
MainFrameActions: Packaging (Windows (64-bit)): WindowsHostPlatform.SetFrameworkVars: BaseVSToolPath=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools
MainFrameActions: Packaging (Windows (64-bit)): WindowsHostPlatform.SetFrameworkVars: Setting VS environment variables via C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\..\..\VC\bin\x86_amd64\vcvarsx86_amd64.bat.
MainFrameActions: Packaging (Windows (64-bit)): CommandUtils.SetEnvVar: SetEnvVar FrameworkDir=C:\Windows\Microsoft.NET\Framework\
MainFrameActions: Packaging (Windows (64-bit)): CommandUtils.SetEnvVar: SetEnvVar FrameworkVersion=v4.0.30319
MainFrameActions: Packaging (Windows (64-bit)): WindowsHostPlatform.SetFrameworkVars: FrameworkDir=C:\Windows\Microsoft.NET\Framework\
MainFrameActions: Packaging (Windows (64-bit)): WindowsHostPlatform.SetFrameworkVars: FrameworkVersion=v4.0.30319
MainFrameActions: Packaging (Windows (64-bit)): ProjectUtils.CleanupFolders: Cleaning up project rules folder
MainFrameActions: Packaging (Windows (64-bit)): CommandUtils.DeleteDirectoryContents: DeleteDirectoryContents(C:\Users\Stew\AppData\Local\Temp\UAT\C+Program+Files+Epic+Games+4.10\Rules)
MainFrameActions: Packaging (Windows (64-bit)): Automation.Process: Compiling scripts.
MainFrameActions: Packaging (Windows (64-bit)): ScriptCompiler.LoadPreCompiledScriptAssemblies: Loading precompiled script DLLs
MainFrameActions: Packaging (Windows (64-bit)): ScriptCompiler.LoadPreCompiledScriptAssemblies: Found 9 script DLL(s).
MainFrameActions: Packaging (Windows (64-bit)): BuildCookRun.SetupParams: Setting up ProjectParams for D:\Dropbox\AAA Recovery\Recovery\Recovery.uproject
MainFrameActions: Packaging (Windows (64-bit)): ProjectUtils.CompileAndLoadTargetsAssembly: Compiling targets DLL: C:\Users\Stew\AppData\Local\Temp\UAT\C+Program+Files+Epic+Games+4.10\Rules\UATRules-74276034.dll
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: Project Params **************
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: AdditionalServerMapParams=
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: Archive=True
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: ArchiveMetaData=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: CreateAppBundle=True
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: BaseArchiveDirectory=C:\Users\Stew\Desktop
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: BaseStageDirectory=D:\Dropbox\AAA Recovery\Recovery\Saved\StagedBuilds
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: Build=True
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: Cook=True
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: Clean=
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: Client=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: ClientConfigsToBuild=Development
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: ClientCookedTargets=Recovery
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: ClientTargetPlatform=Win64
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: Compressed=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: UseDebugParamForEditorExe=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: CookFlavor=
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: CookOnTheFly=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: CookOnTheFlyStreaming=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: UnversionedCookedContent=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: SkipCookingEditorContent=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: NumCookersToSpawn=0
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: GeneratePatch=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: CreateReleaseVersion=
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: BasedOnReleaseVersion=
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: DLCName=
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: DLCIncludeEngineContent=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: AdditionalCookerOptions=
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: DedicatedServer=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: DirectoriesToCook=
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: CulturesToCook=
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: EditorTargets=
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: Foreign=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: IsCodeBasedProject=True
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: IsProgramTarget=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: IterativeCooking=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: CookAll=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: CookMapsOnly=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: Deploy=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: IterativeDeploy=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: FastCook=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: LogWindow=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: Manifests=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: MapToRun=
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: NoClient=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: NumClients=0
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: NoDebugInfo=True
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: NoCleanStage=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: NoXGE=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: MapsToCook=
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: Pak=True
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: Package=True
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: NullRHI=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: FakeClient=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: EditorTest=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: RunAutomationTests=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: RunAutomationTest=
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: RunTimeoutSeconds=0
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: CrashIndex=0
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: ProgramTargets=
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: ProjectBinariesFolder=D:\Dropbox\AAA Recovery\Recovery\Binaries\Win64
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: ProjectBinariesPath=D:\Dropbox\AAA Recovery\Recovery\Binaries\Win64
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: ProjectGameExeFilename=D:\Dropbox\AAA Recovery\Recovery\Binaries\Win64\Recovery.exe
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: ProjectGameExePath=D:\Dropbox\AAA Recovery\Recovery\Binaries\Win64\Recovery.exe
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: Distribution=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: Prebuilt=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: Prereqs=True
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: NoBootstrapExe=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: RawProjectPath=D:\Dropbox\AAA Recovery\Recovery\Recovery.uproject
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: Rocket=True
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: Run=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: ServerConfigsToBuild=Development
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: ServerCookedTargets=
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: ServerTargetPlatform=Win64
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: ShortProjectName=Recovery
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: SignedPak=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: SignPak=
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: SkipCook=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: SkipCookOnTheFly=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: SkipPak=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: SkipStage=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: Stage=True
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: bUsesSteam=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: bUsesCEF3=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: bUsesSlate=True
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: bDebugBuildsActuallyUseDebugCRT=False
MainFrameActions: Packaging (Windows (64-bit)): ProjectParams.ValidateAndLog: Project Params **************
MainFrameActions: Packaging (Windows (64-bit)): Project.Build: ********** BUILD COMMAND STARTED **********
MainFrameActions: Packaging (Windows (64-bit)): UE4Build.Build: XGE was requested, but is unavailable, so we won't use it.
MainFrameActions: Packaging (Windows (64-bit)): UE4Build.Build: ************************* UE4Build:
MainFrameActions: Packaging (Windows (64-bit)): UE4Build.Build: ************************* ForceMonolithic: False
MainFrameActions: Packaging (Windows (64-bit)): UE4Build.Build: ************************* ForceNonUnity:False 
MainFrameActions: Packaging (Windows (64-bit)): UE4Build.Build: ************************* ForceDebugInfo: False
MainFrameActions: Packaging (Windows (64-bit)): UE4Build.Build: ************************* UseXGE: False
MainFrameActions: Packaging (Windows (64-bit)): UE4Build.Build: ************************* UseParallelExecutor: False
MainFrameActions: Packaging (Windows (64-bit)): CommandUtils.Run: Run: C:\Program Files\Epic Games\4.10\Engine\Binaries\DotNET\UnrealBuildTool.exe Recovery Win64 Development  "D:\Dropbox\AAA Recovery\Recovery\Recovery.uproject"  -remoteini="D:\Dropbox\AAA Recovery\Recovery" -noxge -generatemanifest -rocket -NoHotReloadFromIDE
MainFrameActions: Packaging (Windows (64-bit)): CommandUtils.Run: Run: Took 1.5670896s to run UnrealBuildTool.exe, ExitCode=0
MainFrameActions: Packaging (Windows (64-bit)): UE4Build.PrepareManifest: Copied UBT manifest to C:\Users\Stew\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+4.10\UBTManifest.0.xml
MainFrameActions: Packaging (Windows (64-bit)): CommandUtils.Run: Run: C:\Program Files\Epic Games\4.10\Engine\Binaries\DotNET\UnrealBuildTool.exe Recovery Win64 Development  "D:\Dropbox\AAA Recovery\Recovery\Recovery.uproject"  -remoteini="D:\Dropbox\AAA Recovery\Recovery" -noxge -rocket -NoHotReloadFromIDE -ignorejunk
MainFrameActions: Packaging (Windows (64-bit)): UnrealBuildTool: Performing 5 actions (4 in parallel)
MainFrameActions: Packaging (Windows (64-bit)): UnrealBuildTool: JavascriptUMGBlueprintLibrary.cpp
MainFrameActions: Packaging (Windows (64-bit)): UnrealBuildTool: JavascriptOutputDevice.cpp
MainFrameActions: Packaging (Windows (64-bit)): UnrealBuildTool: D:\Dropbox\AAA Recovery\Recovery\Plugins\UnrealJS\Source\V8\Private\JavascriptOutputDevice.cpp(36): error C2039: 'IsUnreachable': is not a member of 'UJavascriptOutputDevice'
MainFrameActions: Packaging (Windows (64-bit)): UnrealBuildTool: D:\Dropbox\AAA Recovery\Recovery\Plugins\UnrealJS\Source\V8\Public\JavascriptOutputDevice.h(46): note: see declaration of 'UJavascriptOutputDevice'
MainFrameActions: Packaging (Windows (64-bit)): UnrealBuildTool: D:\Dropbox\AAA Recovery\Recovery\Plugins\UnrealJS\Source\JavascriptUMG\JavascriptUMGBlueprintLibrary.cpp(59): error C2039: 'FNewLineData': is not a member of 'FTextLayout'
MainFrameActions: Packaging (Windows (64-bit)): UnrealBuildTool: C:\Program Files\Epic Games\4.10\Engine\Source\Runtime\Slate\Public\Framework\Text\ITextLayoutMarshaller.h(6): note: see declaration of 'FTextLayout'
MainFrameActions: Packaging (Windows (64-bit)): UnrealBuildTool: D:\Dropbox\AAA Recovery\Recovery\Plugins\UnrealJS\Source\JavascriptUMG\JavascriptUMGBlueprintLibrary.cpp(59): error C3861: 'FNewLineData': identifier not found
MainFrameActions: Packaging (Windows (64-bit)): UnrealBuildTool: -------- End Detailed Actions Stats -----------------------------------------------------------
MainFrameActions: Packaging (Windows (64-bit)): UnrealBuildTool: ERROR: UBT ERROR: Failed to produce item: D:\Dropbox\AAA Recovery\Recovery\Binaries\Win64\Recovery.pdb
MainFrameActions: Packaging (Windows (64-bit)): UnrealBuildTool: Total build time: 2.62 seconds
MainFrameActions: Packaging (Windows (64-bit)): CommandUtils.Run: Run: Took 2.7861593s to run UnrealBuildTool.exe, ExitCode=5
MainFrameActions: Packaging (Windows (64-bit)): BuildCommand.Execute: ERROR: BUILD FAILED
MainFrameActions: Packaging (Windows (64-bit)): Program.Main: ERROR: AutomationTool terminated with exception:
MainFrameActions: Packaging (Windows (64-bit)): Program.Main: ERROR: Exception in AutomationUtils.Automation: Command failed (Result:5): C:\Program Files\Epic Games\4.10\Engine\Binaries\DotNET\UnrealBuildTool.exe Recovery Win64 Development  "D:\Dropbox\AAA Recovery\Recovery\Recovery.uproject"  -remoteini="D:\Dropbox\AAA Recovery\Recovery" -noxge -rocket -NoHotReloadFromIDE -ignorejunk. See logfile for details: 'UnrealBuildTool-2016.03.25-02.27.36.txt' 
MainFrameActions: Packaging (Windows (64-bit)): Stacktrace:    at AutomationTool.CommandUtils.RunAndLog(String App, String CommandLine, String Logfile, Int32 MaxSuccessCode, String Input, ERunOptions Options, Dictionary`2 EnvVars)
MainFrameActions: Packaging (Windows (64-bit)):    at AutomationTool.CommandUtils.RunUBT(CommandEnvironment Env, String UBTExecutable, String CommandLine, String LogName, Dictionary`2 EnvVars)
MainFrameActions: Packaging (Windows (64-bit)):    at AutomationTool.UE4Build.BuildWithUBT(String ProjectName, String TargetName, UnrealTargetPlatform TargetPlatform, String Config, String UprojectPath, Boolean ForceMonolithic, Boolean ForceNonUnity, Boolean ForceDebugInfo, Boolean ForceFlushMac, Boolean DisableXGE, String InAddAr
MainFrameActions: Packaging (Windows (64-bit)): gs, Boolean ForceUnity, Dictionary`2 EnvVars)
MainFrameActions: Packaging (Windows (64-bit)):    at AutomationTool.UE4Build.Build(BuildAgenda Agenda, Nullable`1 InDeleteBuildProducts, Boolean InUpdateVersionFiles, Boolean InForceNoXGE, Boolean InUseParallelExecutor, Boolean InForceNonUnity, Boolean InForceUnity, Boolean InShowProgress, Dictionary`2 PlatformEnvVars)
MainFrameActions: Packaging (Windows (64-bit)):    at Project.Build(BuildCommand Command, ProjectParams Params, Int32 WorkingCL)
MainFrameActions: Packaging (Windows (64-bit)):    at BuildCookRun.DoBuildCookRun(ProjectParams Params)
MainFrameActions: Packaging (Windows (64-bit)):    at BuildCommand.Execute()
MainFrameActions: Packaging (Windows (64-bit)):    at AutomationTool.Automation.Execute(List`1 CommandsToExecute, CaselessDictionary`1 Commands)
MainFrameActions: Packaging (Windows (64-bit)):    at AutomationTool.Automation.Process(String[] CommandLine)
MainFrameActions: Packaging (Windows (64-bit)):    at AutomationTool.Program.MainProc(Object Param)
MainFrameActions: Packaging (Windows (64-bit)):    at AutomationTool.InternalUtils.RunSingleInstance(Action`1 Main, Object Param)
MainFrameActions: Packaging (Windows (64-bit)):    at AutomationTool.Program.Main()
MainFrameActions: Packaging (Windows (64-bit)): ProcessManager.KillAll: Trying to kill 0 spawned processes.
MainFrameActions: Packaging (Windows (64-bit)): Program.Main: AutomationTool exiting with ExitCode=5
MainFrameActions: Packaging (Windows (64-bit)): Domain_ProcessExit
MainFrameActions: Packaging (Windows (64-bit)): copying UAT log files...
MainFrameActions: Packaging (Windows (64-bit)): RunUAT.bat ERROR: AutomationTool was unable to run successfully.
MainFrameActions: Packaging (Windows (64-bit)): BUILD FAILED
PackagingResults:Error: Error Unknown Error
```

**Comment by Youdaman** [comment]
Just had a thought that maybe I need to update/rebuild the plugin brb.

**Comment by Youdaman** [comment]
I can't seem to build even a blank CPP project with UnrealJS.

Steps to reproduce:

1. download latest Unrealjs
2. create fresh UE4 blank CPP project
3. copy Plugins dir from Unrealjs to project
4. extract v8-msvc2015.zip into Plugins so that v8 has both include and lib dirs
5. right-click MyProject.uproject file and choose Generate VS files
6. open .sln file
7 right-click on MyProject and choose Build

Errors similar to the above in-editor build happen.

Not sure what's going wrong because I recall building a project ok yesterday or the day before.

**Comment by Youdaman** [comment]
Found an "old" version (from the 21st March) of the Unrealjs plugin with the include/lib dirs -- copied that into one of my projects that was failing and now it builds fine. Phew.

I think your merge and rollback on the 22nd of March broke things? https://github.com/ncsoft/Unreal.js/commits/master

Was successfully able to package the project using `Root.ResolveClass('RecoveryPC')` and adding Content/Scripts (which also included a copy of the files from UnrealJS/Content/Scripts) to the "additonal non-asset directories to copy".

And things work as expected in the packaged build! :)

I'll create an extra issue about the build issue (to give others the heads up).

**Comment by Youdaman** [comment]
Thanks again for the tips re packaging @nakosung :)
