### ISSUE TITLE
Jade example is broken

### ISSUE THREAD

**Issue by cl4ws0n** [ncsoft/Unreal.js#79]
I have run `npm i` in the Scripts directory and gotten the node_modules folder. However I get this error when loading the example HelloJade:
```
...
PIE: Info Play in editor start time for /Game/UEDPIE_0_HelloJade 0.181
Javascript:Error: [...]\Content\Scripts\devjade.js:9: TypeError: require(...) is not a function
Javascript:Error: TypeError: require(...) is not a function
Javascript:Error:     at test ([...]\Content\Scripts\devjade.js:9:45)
Javascript:Error:     at [...]\Content\Scripts\devjade.js:45:20
Javascript:Error:     at devrequire.exec ([...]\Content\Scripts\devjade.js:24:34)
Javascript:Error:     at devrequire ([...]\Plugins\UnrealJS\Content\Scripts\devrequire.js:26:19)
Javascript:Error:     at livereload ([...]\Content\Scripts\devjade.js:18:38)
Javascript:Error:     at devjade ([...]\Content\Scripts\devjade.js:44:25)
Javascript:Error:     at main ([...]\Content\Scripts\helloJade.js:35:19)
Javascript:Error:     at [...]\Content\Scripts\helloJade.js:45:46
Javascript:Error:     at invoke_next ([...]/Plugins/UnrealJS/Content/Scripts/polyfill/timers.js:14:9)
Javascript:Error:     at Array.forEach (native)
```

**Comment by nakosung** [comment]
I had implemented several real use cases within jade and angular, I concluded that introduced complexity which is unnecessary. So I dropped to use those tech and now I am happy with low level UMG.

Extension-spiralGenerator.js may be a good example.

Regarding broken example I am sorry that I make confusion.
